### ISSUE TITLE
player/stream-test does not work

### ISSUE THREAD

**Issue by psytechno604** [bitmovin/demos#39]
Just downloaded and opened index.html. Styles not loaded, player not loaded. 

In console: 

index.html:1 A cookie associated with a cross-site resource at http://bitmovin.com/ was set without the `SameSite` attribute. A future release of Chrome will only deliver cookies with cross-site requests if they are set with `SameSite=None` and `Secure`. You can review cookies in developer tools under Application>Storage>Cookies and see more details at https://www.chromestatus.com/feature/5088147346030592 and https://www.chromestatus.com/feature/5633521622188032.

index.html:1 A cookie associated with a cross-site resource at https://bitmovin.com/ was set without the `SameSite` attribute. A future release of Chrome will only deliver cookies with cross-site requests if they are set with `SameSite=None` and `Secure`. You can review cookies in developer tools under Application>Storage>Cookies and see more details at https://www.chromestatus.com/feature/5088147346030592 and https://www.chromestatus.com/feature/5633521622188032.

Does not work from local file system and also from hosting.

**Comment by mhafellner** [comment]
Hey there, thanks for bringing this up. I briefly checked the demo and the two messages you see in the console are just warnings and can be ignored.

The reason you don't see any styling or javascript is because the examples in this repository are not meant to be executed as stand-alone pages. The purpose is to offer the example code for setting up and configuring the player shown on our demo pages. 

For this particular example the public demo page would be https://bitmovin.com/demos/stream-test?format=dash&manifest=https%3A%2F%2Fbitmovin-a.akamaihd.net%2Fcontent%2FMI201109210084_1%2Fmpds%2Ff08e80da-bf1d-4e3d-8899-f0f6155f6efa.mpd

Feel free to use the linked demo page to test your streams. If you are looking for examples how to set up our player I would recommend looking in our docs: https://bitmovin.com/docs/player/quickstarts/get-started-with-the-bitmovin-player
